### ISSUE TITLE
API and SSL outdated for Perforce

### ISSUE THREAD

**Issue by awoodrow-t17** [Unity-Technologies/NativeVersionControlPlugins#12]
Hullo,

I'm a Perforce administrator rather than a developer. I set up a new Perforce server recently which restricts client API version and SSL/TLS version for security. Today I had a developer fail to connect to Perforce using this Unity plugin because it was using P4 API 2016.1, and TLS either 1.0 or 1.1 (not certain which one, but both should be deprecated now).

Is it possible to get someone more familiar with this project to have a look at updating these? 

I've lowered the security on my server as a workaround for now, but this really should be kept more up to date. Upgrading the P4 API should also bring in a number of end-user improvements I expect.

I would love to learn to use Visual Studio and contribute to this myself, but I don't have the resource to do so right now, or the expertise to be confident about doing so.

Thanks,
Alex

**Comment by juliomaqueda** [comment]
Hi @awoodrow-t17, thanks for the feedback.

This improvement is currently pending approval (#16). Please, refer to the PR description for details.
